import { NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";
import { z } from "zod";

// 1. Define schema for the editor layout configuration
const elementTransformSchema = z.object({
  x: z.number(),
  y: z.number(),
  scale: z.number(),
  rotation: z.number(),
  opacity: z.number().min(0).max(1),
  zIndex: z.number()
});

const layoutSchema = z.record(z.string(), elementTransformSchema);

export async function POST(req: Request) {
  // Security check: Only allow in development mode or if explicitly enabled
  if (process.env.NODE_ENV !== "development" && process.env.NEXT_PUBLIC_EDITOR_MODE !== "true") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  try {
    const rawBody = await req.json();
    
    // 2. Validate incoming data against the Zod schema
    const layout = layoutSchema.parse(rawBody);

    const fileContent = `export interface ElementTransform {
  x: number;
  y: number;
  scale: number;
  rotation: number;
  opacity: number;
  zIndex: number;
}

export type IncentivesLayoutConfig = Record<string, ElementTransform>;

export const defaultTransform: ElementTransform = {
  x: 0,
  y: 0,
  scale: 1,
  rotation: 0,
  opacity: 1,
  zIndex: 10,
};

// AUTO-GENERATED BY VISUAL EDITOR
export const incentivesLayout: IncentivesLayoutConfig = ${JSON.stringify(layout, null, 2)};
`;

    const filePath = path.join(process.cwd(), "src", "config", "incentives-layout.ts");
    await fs.writeFile(filePath, fileContent, "utf8");

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Failed to save layout:", error);
    
    // 3. Handle validation errors specifically
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Invalid input data", details: error.issues }, 
        { status: 400 }
      );
    }
    
    return NextResponse.json({ error: "Failed to save layout" }, { status: 500 });
  }
}
